apiVersion: triliovault.trilio.io/v1
kind: Restore
metadata:
  name: demo-restore
spec:
  source:
    type: Backup
    backup:
      name: mysql-label-backup
  transformComponents:
    custom:
    - transformName: t1
      resources:
        groupVersionKind:
          group: ""
          version: v1
          kind: Service
        objects:
          - k8s-demo-app-frontend
          - k8s-demo-app-mysql
      jsonPatches:
        - op: remove
          path: "/spec/clusterIPs"
  restoreNamespace: demotarget
  skipIfAlreadyExists: true
